### ISSUE TITLE
empty sitemap since 4.1.0

### ISSUE THREAD

**Issue by guy-confetti** [nuxt-modules/robots#137]
I'm using `@nuxtjs/sitemap@6`, and since updating `@nuxtjs/robots` to [4.1.0](https://github.com/nuxt-modules/robots/releases/tag/v4.1.0) the sitemap.xml returns empty.

see: https://stackblitz.com/edit/nuxt-starter-uk5gcm

**Comment by harlan-zw** [comment]
Thank you for reporting this, I've pushed up a fix in v4.1.1.

**Comment by guy-confetti** [comment]
Thanks for the quick response! I've updated to v4.1.1 but I'm still experiencing the issue. production build or order of modules does not affect it. do I need to enable it somehow?

https://stackblitz.com/edit/nuxt-starter-uk5gcm

**Comment by Skyost** [comment]
Same problem here. Example stacktrace : https://github.com/Skyost/MesCoursDeMaths/actions/runs/10469819778/job/28993654625#step:6:3427.

**Comment by felixranesberger** [comment]
Same problem here, downgrading to 4.0.2 fixed it: 

Works using `@nuxtjs/seo@^2.0.0-rc.18` in combination with downgraded `@nuxtjs/robots@4.0.2`

**Comment by harlan-zw** [comment]
I'm very sorry about this, it seems like I was missing test coverage on the robot meta tag in production. I've pushed up a fix in v4.1.2 and will release a Nuxt SEO release with this patch now as well.

**Comment by felixranesberger** [comment]
No Problem, thanks for the quick fix!

**Comment by Skyost** [comment]
Is the bug fixed for you @felixranesberger ? I have the same problem, even with `v4.1.2`...

**Comment by felixranesberger** [comment]
Just tried out the new version of `@nuxtjs/seo@^2.0.0-rc.19` which uses `@nuxtjs/robots@4.1.3` and everything seems to work. 

`sitemap.xml` is filled with entries, also `robots.txt` and `robots-meta-tag` seems to work just fine, so no issues on my side.

**Comment by harlan-zw** [comment]
Thanks for confirming @felixranesberger.

I've tested using Stackblitz to also confirm the issue is solved: https://stackblitz.com/edit/nuxt-starter-kjedrj?file=package.json

Again sorry for the issue, I was moving house yesterday so thought I could just quickly push up a fix but I missed the case of not having any robot rules. Test cases now cover this properly.
